version: '3.8'

services:

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart:
      always

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: likes
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
  